export const plans = [
    {
        id: 'simple-plus',
        rank: 2,
        name: {
            ko: '유학생 선호도 1위 넉넉한 데이터 플랜',
            en: 'Student Favorite #1 Data Plan',
            zh: '留학생 首选 充足流量套餐',
            vi: 'Gói dữ liệu số 1 cho du học sinh'
        },
        originalPrice: 61000,
        price: 24750,
        data: '41GB',
        qos: '1Mbps',
        tethering: '41GB',
        calls: 'Unlimited',
        extraCalls: '300m',
        youth: true,
        tags: ['sale'],
        isBest: false
    },
    {
        id: 'data-regular-youth',
        rank: 1,
        name: {
            ko: '고화질 영상 시청용 대용량 데이터 전용',
            en: 'High-Res Video Data Pack',
            zh: '高清视频大容量套餐',
            vi: 'Gói dung lượng cao xem video'
        },
        originalPrice: 63000,
        price: 25500,
        data: '70GB',
        qos: '1Mbps',
        tethering: '45GB',
        calls: 'Unlimited',
        extraCalls: '300m',
        youth: true,
        tags: ['best', 'sale'],
        isBest: true
    },
    {
        id: 'standard-essential-youth',
        rank: 3,
        name: {
            ko: '집에서도 와이파이 없이 무제한급 데이터',
            en: 'Home Data Freedom Pack',
            zh: '居家流量自由 准无限套餐',
            vi: 'Gói dữ liệu tự do tại nhà'
        },
        originalPrice: 70000,
        price: 29500,
        data: '185GB',
        qos: '5Mbps',
        tethering: '60GB',
        calls: 'Unlimited',
        extraCalls: '300m',
        youth: true,
        tags: ['sale'],
        isBest: false
    },
    {
        id: 'standard-youth',
        rank: 4,
        name: {
            ko: '데이터 걱정 없는 유학생 끝판왕 전용',
            en: 'Ultimate Student Freedom Plan',
            zh: '留학생 终极流量王 专用套餐',
            vi: 'Gói cước tối thượng cho du học sinh'
        },
        originalPrice: 75000,
        price: 33250,
        data: '210GB',
        qos: '5Mbps',
        tethering: '65GB',
        calls: 'Unlimited',
        extraCalls: '300m',
        youth: true,
        tags: ['sale'],
        isBest: false
    }
];

export const translations = {
    en: {
        todayDeal: "New Semester Special",
        airportPickup: "Airport Pickup & eSIM Ready",
        arrivalGuide: "Instant activation upon arrival at Korea airport",
        selectLanguage: 'Language',
        youthBadge: 'Youth',
        data: 'Data',
        calls: 'Calls',
        price: 'Price',
        originalPrice: 'Reg.',
        month: '/ mo',
        applyNow: 'Register for this Plan',
        unlimited: 'Unlimited',
        best: 'BEST',
        sale: 'Special',
        semesterBanner: "🌸 Limited Offer for New Semester Students",
        guarantee: 'Lowest Price for 12 Mo.',
        lowestPriceBadge: "100% Lowest Price Guarantee",
        lowestPriceReason: "If you find a cheaper price for the same spec, we provide a full refund.",
        modalHeader: "Select your SIM type",
        modalSubtitle: "Choose between USIM and eSIM as you like.",
        soldOutHeader: "Oops! This plan is sold out.",
        soldOutSubtitle: "Due to high demand, the new semester special for this plan has closed.",
        comingSoonDesc: "Leave your email and we'll notify you when it's back!",
        tabs: {
            benefits: "Benefits",
            details: "Plan Specs"
        },
        fields: {
            baseData: "Base Data",
            qos: "QoS Speed",
            tethering: "Tethering",
            calls: "Calls",
            video: "Extra Calls",
            intl: "Intl. Call",
            sms: "SMS"
        },
        spamProtection: "Spam Block",
        applied: "Applied",
        features: {
            f1Title: "USIM & eSIM Supported",
            f1Desc: "Compatible with all unlocked devices",
            f2Title: "Real-time Spam Filter",
            f2Desc: "24/7 protection against phishing",
            f3Title: "Unlimited Calls/SMS",
            f3Desc: "Stay connected with family and friends"
        },
        close: "Close",
        successMsg: "✔️ We will notify you back!"
    },
    zh: {
        todayDeal: "开学季特惠",
        airportPickup: "机场领取 & eSIM 即刻开通",
        arrivalGuide: "抵达韩国机场后即可立即开通使用",
        selectLanguage: '语言',
        youthBadge: 'Youth',
        data: '流量',
        calls: '通话',
        price: '价格',
        originalPrice: '标准价',
        month: '/ 月',
        applyNow: '申请此套装',
        unlimited: '不限量',
        best: '最佳',
        sale: '特惠',
        semesterBanner: "🌸 开学季留学生限定特惠活动",
        guarantee: '12个月内享受此最低价',
        lowestPriceBadge: "100% 全网最低价保证",
        lowestPriceReason: "若发现同等配置价格更低，我们承诺全额退款。",
        modalHeader: "请选择您的 SIM 卡类型",
        modalSubtitle: "USIM 或 eSIM 均可根据您的需求选择。",
        soldOutHeader: "抱歉！此套装已售罄。",
        soldOutSubtitle: "由于申请人数众多，本阶段特惠名额已满。",
        comingSoonDesc: "留下您的邮箱，有名额时我们将第一时间通知您。",
        tabs: {
            benefits: "专享权益",
            details: "套装详情"
        },
        fields: {
            baseData: "基础流量",
            qos: "限速速度",
            tethering: "热点分享",
            calls: "语音通话",
            video: "附加通话",
            intl: "国际长途",
            sms: "短信息"
        },
        applied: "已启用",
        features: {
            f1Title: "支持 USIM & eSIM",
            f1Desc: "适用于所有已解锁的智能手机",
            f2Title: "实时垃圾信息拦截",
            f2Desc: "24小时全天候防范电信诈骗",
            f3Title: "通话 & 短信不限量",
            f3Desc: "随时随地畅联无阻"
        },
        close: "关闭",
        successMsg: "✔️ 有名额时我们将立即通知您！"
    },
    vi: {
        todayDeal: "Khuyến mãi học kỳ mới",
        airportPickup: "Nhận tại sân bay & eSIM Có sẵn",
        arrivalGuide: "Kích hoạt ngay khi vừa đến sân bay Hàn Quốc",
        selectLanguage: 'Ngôn ngữ',
        youthBadge: 'Youth',
        data: 'Dữ liệu',
        calls: 'Gọi điện',
        price: 'Giá',
        originalPrice: 'Giá gốc',
        month: '/ tháng',
        applyNow: 'Sử dụng gói này',
        unlimited: 'Không giới hạn',
        best: 'TỐT NHẤT',
        sale: 'Ưu đãi',
        semesterBanner: "🌸 Chương trình ưu đãi học kỳ mới cho du học sinh",
        guarantee: 'Giá thấp nhất trong 12 tháng',
        lowestPriceBadge: "Cam kết giá thấp nhất 100%",
        lowestPriceReason: "Hoàn tiền toàn bộ nếu tìm thấy giá rẻ hơn cho cùng cấu hình.",
        modalHeader: "Chọn loại SIM của bạn",
        modalSubtitle: "Hỗ trợ cả USIM và eSIM theo ý muốn của bạn.",
        soldOutHeader: "Rất tiếc! Gói cước đã hết suất.",
        soldOutSubtitle: "Do số lượng đăng ký quá lớn, ưu đãi học kỳ mới đã kết thúc.",
        comingSoonDesc: "Hãy để lại email, chúng tôi sẽ báo cho bạn khi có suất mới!",
        tabs: {
            benefits: "Ưu đãi",
            details: "Chi tiết gói"
        },
        fields: {
            baseData: "Dữ liệu gốc",
            qos: "Tốc độ QoS",
            tethering: "Chia sẻ mạng",
            calls: "Gọi thoại",
            video: "Cuộc gọi phụ",
            intl: "Gọi quốc tế",
            sms: "Tin nhắn"
        },
        applied: "Đang áp dụng",
        features: {
            f1Title: "Hỗ trợ USIM & eSIM",
            f1Desc: "Tương thích với mọi dòng máy quốc tế",
            f2Title: "Chặn Spam & Lừa đảo",
            f2Desc: "Bảo vệ thông tin cá nhân 24/7",
            f3Title: "Gọi & Nhắn tin thả ga",
            f3Desc: "Không giới hạn kết nối bạn bè"
        },
        close: "Đóng",
        successMsg: "✔️ Chúng tôi sẽ sớm liên hệ lại!"
    },
    ko: {
        todayDeal: "신학기 특가 핫딜",
        airportPickup: "공항 수령 및 eSIM 즉시 개통",
        arrivalGuide: "입국 전 신청하면 입국하자마자 바로 사용 가능",
        selectLanguage: '언어',
        youthBadge: '유쓰',
        data: '데이터',
        calls: '통화',
        price: '가격',
        originalPrice: '정가',
        month: '/ 월',
        applyNow: '이 요금제로 신청하기',
        unlimited: '무제한',
        best: 'BEST 인기',
        sale: '특가',
        semesterBanner: "🌸 유학생을 위한 신학기 한정 특가 캠페인",
        guarantee: '12개월 동안 최저가 보장',
        lowestPriceBadge: "100% 최저가 보상제",
        lowestPriceReason: "동일 스펙 기준 최저가가 아닐 경우 무조건 환불해 드립니다.",
        modalHeader: "유심 타입을 선택해 주세요",
        modalSubtitle: "일반 USIM과 eSIM 중 원하는 방식 선택이 가능합니다.",
        soldOutHeader: "이미 판매가 마감된 플랜입니다.",
        soldOutSubtitle: "신학기 전용 한정 수량이 모두 소진되어 신청이 조기 종료되었습니다.",
        comingSoonDesc: "이메일을 남겨주시면 추가 물량 확보 시 알려드릴게요.",
        tabs: {
            benefits: "공통 혜택",
            details: "요금제 상세"
        },
        fields: {
            baseData: "기본 제공 데이터",
            qos: "소진 시 속도",
            tethering: "쉐어링·테더링 데이터",
            calls: "음성 통화",
            video: "영상/부가통화",
            intl: "국제 전화",
            sms: "문자"
        },
        spamProtection: "스팸 차단",
        applied: "적용",
        features: {
            f1Title: "USIM / eSIM 모두 지원",
            f1Desc: "원하는 방식으로 자유로운 가입 및 개통",
            f2Title: "보이스피싱 실시간 방지",
            f2Desc: "개인정보 유출 차단으로 24시간 활성화",
            f3Title: "음성 통화 & 문자 무제한",
            f3Desc: "추가 요금 걱정 없이 무제한 사용 가능"
        },
        close: "닫기",
        successMsg: "✔️ 추가 물량 확보 시 메일로 알려드릴게요!"
    }
};
